export const SET_PAGE_TITLE = "SET_PAGE_TITLE";
export const SET_CURRENT_LEFT_SIDEBAR_ITEM = "SET_CURRENT_LEFT_SIDEBAR_ITEM";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const RESET_POSTS = "RESET_POSTS";
export const FETCH_POSTS_DONE = "FETCH_POSTS_DONE";
export const SET_SEARCH_CONTENT = "SET_SEARCH_CONTENT";
export const SHOW_POST_DETAIL = "SHOW_POST_DETAIL";
export const HIDE_POST_DETAIL = "HIDE_POST_DETAIL";

export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_UP = "SIGN_UP";
export const ALERT_NOTIFICATION = "ALERT_NOTIFICATION";
